apiVersion: v1
kind: Service
metadata:
  name: simple-docker-app-service
  labels:
    app: simple-docker-app
spec:
  type: LoadBalancer
  selector:
    app: simple-docker-app
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-docker-app-deployment
  labels:
    app: simple-docker-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-docker-app
  template:
    metadata:
      labels:
        app: simple-docker-app
    spec:
      containers:
        - name: simple-docker-app
          image: simple-docker-app-image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8010
