apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  namespace: default
  labels:
    app: {{ .Values.appName }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.appName }}
  ports:
    - port: 8080
      targetPort: 8080